import {
  Braces,
  Binary,
  Link as LinkIcon,
  KeyRound,
  Fingerprint,
  Hash,
  Clock,
  Palette,
  Regex,
  FileText,
  FileDiff,
  Type,
  CaseSensitive,
  CalendarDays,
  List,
  Code2,
  QrCode,
  Calculator
} from "lucide-react";

export const tools = [
  { id: "json", name: "JSON Formatter", description: "Format, minify, and validate JSON data", path: "/json", icon: Braces },
  { id: "base64", name: "Base64 Encode/Decode", description: "Encode and decode text to Base64", path: "/base64", icon: Binary },
  { id: "url", name: "URL Encode/Decode", description: "Encode and decode URL-safe strings", path: "/url", icon: LinkIcon },
  { id: "jwt", name: "JWT Decoder", description: "Decode JSON Web Tokens", path: "/jwt", icon: KeyRound },
  { id: "uuid", name: "UUID Generator", description: "Generate v4 UUIDs", path: "/uuid", icon: Fingerprint },
  { id: "hash", name: "Hash Generator", description: "Generate MD5, SHA-1, SHA-256 hashes", path: "/hash", icon: Hash },
  { id: "timestamp", name: "Timestamp Converter", description: "Convert Unix timestamps to dates", path: "/timestamp", icon: Clock },
  { id: "color", name: "Color Converter", description: "Convert between HEX, RGB, and HSL", path: "/color", icon: Palette },
  { id: "regex", name: "Regex Tester", description: "Test regular expressions against text", path: "/regex", icon: Regex },
  { id: "markdown", name: "Markdown Preview", description: "Write and preview Markdown", path: "/markdown", icon: FileText },
  { id: "diff", name: "Text Diff", description: "Compare two texts and highlight differences", path: "/diff", icon: FileDiff },
  { id: "lorem", name: "Lorem Ipsum", description: "Generate placeholder text", path: "/lorem", icon: Type },
  { id: "case", name: "Case Converter", description: "Convert text between cases", path: "/case", icon: CaseSensitive },
  { id: "cron", name: "Cron Explainer", description: "Parse cron expressions to readable text", path: "/cron", icon: CalendarDays },
  { id: "querystring", name: "Query String Parser", description: "Parse and build URL query strings", path: "/querystring", icon: List },
  { id: "beautifier", name: "Code Beautifier", description: "Format HTML, CSS, and JS", path: "/beautifier", icon: Code2 },
  { id: "qrcode", name: "QR Code Generator", description: "Generate QR codes from text or URLs", path: "/qrcode", icon: QrCode },
  { id: "base-converter", name: "Base Converter", description: "Convert numbers between bases", path: "/base-converter", icon: Calculator },
];
